name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: andrea-avo
          template: classic
          
          # Base content (Followers & User Account Stats)
          base: header, community, repositories, metadata
          
          # Isometric Commit Calendar (Tampilan 3D)
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          
          # Commit Calendar (Tampilan kalender standar)
          plugin_calendar: yes
          plugin_calendar_limit: 1
          
          # Repository Licenses (Menampilkan lisensi yang Anda gunakan)
          plugin_licenses: yes
          plugin_licenses_setup: npm install
          
          # Repository Traffic (Statistik pengunjung repo Anda)
          plugin_traffic: yes

          # Tambahan agar Bahasa tetap muncul
          plugin_languages: yes
          plugin_languages_sections: most-used
