- uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: andrea-avo
          template: classic
          base: header, community, repositories, metadata
          config_timezone: Asia/Jakarta
          plugin_languages: yes
          plugin_languages_details: lines, percentage
          plugin_languages_sections: most-used
          plugin_languages_indepth: yes
          plugin_languages_limit: 0  
          config_display: large
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_traffic: yes
          plugin_people: yes
          plugin_people_types: followers, following
          plugin_licenses: yes
