name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: andrea-avo
          template: classic
          
          # Pengaturan Tampilan & Warna
          config_display: columns         # Membagi tampilan jadi 2 kolom
          config_timezone: Asia/Jakarta
          config_padding: 0, 5%
          
          # 1. Base Stats
          base: header, community, repositories, metadata
          
          # 2. Isometric Calendar (Hiasan 3D)
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          
          # 3. Languages (Dengan Animasi)
          plugin_languages: yes
          plugin_languages_sections: most-used
          plugin_languages_details: bytes-size, percentage
          plugin_languages_animations: yes
          
          # 4. Habits (Grafik Aktivitas)
          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_charts: yes
          
          # 5. Achievements (Lencana/Badge)
          plugin_achievements: yes
          plugin_achievements_display: compact
          
          # 6. Traffic & People
          plugin_traffic: yes
          plugin_people: yes
          plugin_people_types: followers, following
          plugin_people_limit: 28
          
          # 7. Licenses
          plugin_licenses: yes
