name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      # 1. Lowlighter Metrics
      - name: General Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: andrea-avo
          template: classic
          base: header, community, repositories, metadata
          config_timezone: Asia/Jakarta
          plugin_traffic: yes
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_people: yes
          plugin_people_types: followers, following
          plugin_people_limit: 30
          plugin_licenses: yes

      # 2. Language Analytics (Sudah diperbaiki ke jstct)
      - name: GitHub Profile Language Analytics
        uses: jstct/github-profile-language-analytics@v2.4.0
        with:
          token: ${{ secrets.METRICS_TOKEN }}
