name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: andrea-avo
          template: classic
          base: header, community, repositories, metadata
          config_timezone: Asia/Jakarta

          # 1. Isometric Commit Calendar
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

          # 2. Language Analytics 
          plugin_languages: yes                       
          plugin_languages_details: bytes-size, percentage, lines      
          plugin_languages_sections: most-used
          plugin_languages_limit: 20
          
          # 3. Penyesuaian Visual & Dark Mode
          config_order: base.header, isocalendar, languages, base.community

          # 4. Plugin tambahan Anda
          plugin_traffic: yes
          plugin_people: yes
          plugin_people_types: followers, following
          plugin_licenses: yes
