name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: andrea-avo
          template: classic
         
          base: header, community, repositories, metadata
          config_timezone: Asia/Jakarta

          # 1. Statistik Pengunjung
          plugin_traffic: yes

          # 2. Isometric Commit Calendar
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

          # 3. Bahasa Pemrograman
          plugin_languages: yes
          plugin_languages_details: bytes-size, percentage
          plugin_languages_limit: 20
          plugin_languages_sections: most-used
          
          # 4. People
          plugin_people: yes
          plugin_people_types: followers, following
          plugin_people_limit: 30
          plugin_people_size: 30
          plugin_people_shuffle: yes 

          # 5. Licenses
          plugin_licenses: yes
          plugin_licenses_ratio: yes
